### ISSUE TITLE
Card not displayed correctly

### ISSUE THREAD

**Issue by hughesba** [Rocka84/dual-gauge-card#10]
I have recently setup this card, but its not displaying as expected. I am running HA v0.92.2, viewing from Chrome browser on Windows, and the same sensors are displaying correct values on the custom:plan-coordinates card. Any ideas would be greatly appreciated

![image](https://user-images.githubusercontent.com/50526723/57574085-4e24e500-742a-11e9-81bb-6352d20e9bef.png)

From ui-lovelace.yaml:

![image](https://user-images.githubusercontent.com/50526723/57574157-8d076a80-742b-11e9-8bf5-ec77cb56c748.png)

**Comment by Rocka84** [comment]
Hi!  
I'll have to look into this when I find the time, hopefully this weekend. Seems to be a minor css error.  

Btw: I'm using this card myself on the same version of HA and - in my setup - had no issues yet. So thank you very much for telling me about this and not just walking away!

Rocka84

**Comment by Rocka84** [comment]
After reading your yaml again: Are you sure that the entities you use, do have the attributes you configured?
At least that would explain it, if your "sensor.dark_sky_temperature" doesn't have an attribute "current_temperature", the value is "undefined".

I think what you want is to use the state of the entity, instead of one its attributes. In that case just drop the "attribute:" lines from your config.

**Comment by hughesba** [comment]
Thanks Rocka84 that was it ... commented out the attribute lines and all working fine. Thanks for your help.

**Comment by akhlghatyan** [comment]
remove attribute value
